### ISSUE TITLE
Random agent(s) by country

### ISSUE THREAD

**Issue by rudimk** [rudimk/PyPplAPI#2]
Need to add a class for grabbing an agent/list of agents for a given country code, from pplapi.

**Comment by sudhirmishra** [comment]
For this to be modular, it makes sense to refractor `Agent` class into `__init__` functions to some `AgentAPI` class. 

![pypplapi](https://cloud.githubusercontent.com/assets/4728439/23691014/e4fadaae-03eb-11e7-9126-0f86ab858472.png)
